sc_metadata_file:
  files:
    '0':
    - ''
    - Rambow_dataset
    - data_info.rds
  root: ..
m_time_column: Age
m_time_points:
- before treatment
- 4d on treatment
- 28d on treatment
- 57d on treatment
m_id_column: Run
