dp_out_dir:
  path:
  - ''
  - Rambow_dataset
  - sam_out
  root: ..
dp_samtools_exec_dir:
  path:
  - ''
  - usr
  - bin
  root: Computer
dp_bam_dir:
  path:
  - ''
  - Rambow_dataset
  - bam
  root: ..
dp_mut_dir:
  path:
  - ''
  - Rambow_dataset
  - filtered_vcf
  root: ..
