inf_num_iter: 10000
inf_num_rs: 50
inf_n_try_bs: 500
inf_num_processes: 10
inf_seed: 1121
inf_random_tree: no
inf_marginalize: no
inf_keep_equivalent: no
inf_check_indistinguishable: no
inf_show: yes
inf_learning_rate: 1
inf_error_move: no
inf_alpha:
  '':
  - alpha_1
  - alpha_2
  - alpha_3
  Var.2:
  - alpha_1
  - alpha_2
  - alpha_3
  before treatment:
  - '0.02'
  - '0.10'
  - .na.character
  4d on treatment:
  - '0.01'
  - '0.05'
  - .na.character
  28d on treatment:
  - '0.01'
  - '0.05'
  - .na.character
  57d on treatment:
  - '0.01'
  - '0.05'
  - .na.character
inf_beta:
  '':
  - beta_1
  - beta_2
  - beta_3
  Var.2:
  - beta_1
  - beta_2
  - beta_3
  before treatment:
  - '0.1'
  - '0.1'
  - .na.character
  4d on treatment:
  - '0.05'
  - '0.05'
  - .na.character
  28d on treatment:
  - '0.05'
  - '0.05'
  - .na.character
  57d on treatment:
  - '0.05'
  - '0.05'
  - .na.character
inf_params:
  D:
    before treatment:
    - 1.0
    - 1.0
    - 1.0
    - .na.real
    - .na.real
    - 0.0
    4d on treatment:
    - .na.real
    - 0.0
    - 0.0
    - 1.0
    - .na.real
    - .na.real
    28d on treatment:
    - 1.0
    - .na.real
    - .na.real
    - 1.0
    - .na.real
    - .na.real
    57d on treatment:
    - 0.0
    - 1.0
    - 1.0
    - 1.0
    - .na.real
    - 1.0
  learning_rate: 1
  num_iter: 10000
  num_rs: 50
  n_try_bs: 500
  num_processes: 10
  seed: 1121
  random_tree: no
  marginalize: no
  keep_equivalent: no
  check_indistinguishable: no
  error_move: no
  show: no
  alpha:
    alpha_1:
    - 0.02
    - 0.01
    - 0.01
    - 0.01
    alpha_2:
    - 0.1
    - 0.05
    - 0.05
    - 0.05
  beta:
    beta_1:
    - 0.1
    - 0.05
    - 0.05
    - 0.05
    beta_2:
    - 0.1
    - 0.05
    - 0.05
    - 0.05
inf_alpha_cell_edit:
  row: -1.0
  col: -1.0
  value: 0.0
inf_beta_cell_edit:
  row: -1.0
  col: -1.0
  value: 0.0
